variables:
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vatcsuite
      MYSQL_USER: vatcsuite
      MYSQL_PASSWORD: vatcsuite
    ports:
      - 3306:3306

pipeline:
  - name: Testing
    image: sineverba/php8xc:latest
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: vatcsuite
      DB_USERNAME: vatcsuite
      DB_PASSWORD: vatcsuite
      APP_KEY: base64:YXJkIGF0IGEgZGVjb2RlIGJhc2U2NCBzdHJpbmc=
    commands:
      - cd ./src
      - composer install
      - php artisan test
      - cd ../

  - name: Generate version file
    image: alpine/git
    commands:
      - cd ./src
      - git describe --always --tags --dirty > version
      - cat version
      - cd ../

  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/vatcsuite
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/vatcsuite
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG}"]
    when:
      event: tag

  - name: Deploy Pull Request
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/vatcsuite
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request

branches: [main, release/*]
ignore_paths: [README.md, LICENSE, .github, .gitignore]
