when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64,linux/arm64"
  - &node_image "node:18"

steps:
  - name: Generate version file
    image: alpine/git
    commands:
      - cd ./src
      - git describe --always --tags --dirty > version
      - cat version
      - cd ../

  - name: Deploy to CapRover
    image: *node_image
    secrets: [caprover_password, caprover_url, caprover_name]
    commands:
      - npm install -g caprover
      - caprover login
      - caprover deploy -n caprover -a atis -b main
    when:
      event: tag

  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/vatcsuite
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/vatcsuite
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG}"]
    when:
      event: tag

  - name: Deploy Pull Request
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/vatcsuite
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request

depends_on:
  - test
